import { and, eq, sql } from "drizzle-orm";
import type { Db } from "@zeroinc/db";
import { issues } from "@zeroinc/db";
import { issueService } from "./issues.js";
import { logActivity } from "./activity-log.js";
import { productCouncilService, type ProductCouncilProposalDebate } from "./product-council.js";

export type ProductCouncilMaterializeActor = {
  actorType: "agent" | "user" | "system";
  actorId: string;
  agentId?: string | null;
  runId?: string | null;
};

export type MaterializeProductCouncilOptions = {
  goalId?: string | null;
  maxProposals?: number;
  dryRun?: boolean;
  targetStatus?: "backlog" | "todo";
  ensureMacroPrograms?: boolean;
  actor: ProductCouncilMaterializeActor;
};

export type MaterializeProductCouncilResult = {
  generated: number;
  skipped: number;
  dryRun: boolean;
  reason: string;
  report: Awaited<ReturnType<ReturnType<typeof productCouncilService>["analyze"]>>;
  createdIssues: Array<{ id: string; identifier: string; title: string }>;
  skippedProposals: Array<{ proposalId: string; title: string; reason: string }>;
};

function renderDebateSection(debate: ProductCouncilProposalDebate | undefined) {
  if (!debate) return "";

  const mustHaves = debate.speakers
    .flatMap((speaker) => speaker.mustHave)
    .filter((value, index, array) => value && array.indexOf(value) === index);
  const speakerLines = debate.speakers.map((speaker) =>
    `- ${speaker.role.toUpperCase()} (${speaker.speaker}): ${speaker.stance} — ${speaker.rationale}`);
  const mustHaveLines = mustHaves.map((item) => `- ${item}`);

  return (
    "## Specialist Debate\n" +
    `Consensus: ${debate.consensus.toUpperCase()} (confidence ${debate.confidence}%)\n\n` +
    `${debate.summary}\n\n` +
    "### Positions\n" +
    `${speakerLines.join("\n")}\n\n` +
    (mustHaveLines.length > 0
      ? `### Must-Haves\n${mustHaveLines.join("\n")}\n\n`
      : "")
  );
}

function buildIssueDescription(
  reportTimestamp: string,
  proposal: Awaited<ReturnType<ReturnType<typeof productCouncilService>["analyze"]>>["proposals"][number],
  debate: ProductCouncilProposalDebate | undefined,
) {
  const definitionOfDone = proposal.definitionOfDone
    .map((item) => `- ${item}`)
    .join("\n");
  const debateSection = renderDebateSection(debate);

  return (
    `${proposal.description}\n\n` +
    `Suggested owner role: ${proposal.suggestedOwnerRole ?? "n/a"}\n` +
    `Suggested assignee: ${proposal.suggestedAssigneeName ?? "n/a"}\n\n` +
    "## Definition of Done\n" +
    `${definitionOfDone}\n\n` +
    debateSection +
    `Generated by Product Council at ${reportTimestamp}.`
  );
}

export async function materializeProductCouncilProposals(
  db: Db,
  companyId: string,
  opts: MaterializeProductCouncilOptions,
): Promise<MaterializeProductCouncilResult> {
  const council = productCouncilService(db);
  const issuesSvc = issueService(db);
  const targetStatus = opts.targetStatus === "todo" ? "todo" : "backlog";

  const report = await council.analyze(companyId, {
    goalId: opts.goalId ?? undefined,
    maxProposals: opts.maxProposals,
    ensureMacroPrograms: opts.ensureMacroPrograms ?? true,
  });

  if (!report.gating.shouldGenerate) {
    return {
      generated: 0,
      skipped: report.proposals.length,
      dryRun: Boolean(opts.dryRun),
      reason: report.gating.reason,
      report,
      createdIssues: [],
      skippedProposals: [],
    };
  }

  if (opts.dryRun === true) {
    return {
      generated: 0,
      skipped: 0,
      dryRun: true,
      reason: report.gating.reason,
      report,
      createdIssues: [],
      skippedProposals: [],
    };
  }

  const openRows = await db
    .select({
      id: issues.id,
      title: issues.title,
    })
    .from(issues)
    .where(
      and(
        eq(issues.companyId, companyId),
        sql`${issues.status} in ('backlog','todo','in_progress','in_review','blocked')`,
        sql`${issues.hiddenAt} is null`,
      ),
    )
    .limit(400);

  const openTitleSet = new Set(openRows.map((row) => row.title.trim().toLowerCase()));
  const createdIssues: Array<{ id: string; identifier: string; title: string }> = [];
  const skippedProposals: Array<{ proposalId: string; title: string; reason: string }> = [];
  const debateByProposalId = new Map(
    (report.proposalDebate?.items ?? []).map((item) => [item.proposalId, item]),
  );

  for (const proposal of report.proposals) {
    const normalizedTitle = proposal.title.trim().toLowerCase();
    if (!normalizedTitle || openTitleSet.has(normalizedTitle)) {
      skippedProposals.push({
        proposalId: proposal.id,
        title: proposal.title,
        reason: "duplicate_open_title",
      });
      continue;
    }

    const debate = debateByProposalId.get(proposal.id);
    if (debate?.consensus === "hold") {
      skippedProposals.push({
        proposalId: proposal.id,
        title: proposal.title,
        reason: "debate_hold",
      });
      continue;
    }

    const created = await issuesSvc.create(companyId, {
      title: proposal.title,
      description: buildIssueDescription(report.timestamp, proposal, debate),
      status: targetStatus,
      priority: proposal.priority,
      goalId: report.goal?.id ?? null,
      originKind: "manual",
      createdByAgentId: opts.actor.agentId ?? null,
      createdByUserId: opts.actor.actorType === "user" ? opts.actor.actorId : null,
    });

    openTitleSet.add(normalizedTitle);
    createdIssues.push({
      id: created.id,
      identifier: created.identifier ?? created.id,
      title: created.title,
    });

    await logActivity(db, {
      companyId,
      actorType: opts.actor.actorType,
      actorId: opts.actor.actorId,
      agentId: opts.actor.agentId ?? null,
      runId: opts.actor.runId ?? null,
      action: "issue.created",
      entityType: "issue",
      entityId: created.id,
      details: {
        title: created.title,
        identifier: created.identifier,
        source: "product_council",
        proposalId: proposal.id,
        sourceMilestoneId: proposal.sourceMilestoneId,
        debateConsensus: debate?.consensus ?? null,
        debateConfidence: debate?.confidence ?? null,
      },
    });
  }

  return {
    generated: createdIssues.length,
    skipped: skippedProposals.length,
    dryRun: false,
    reason: report.gating.reason,
    report,
    createdIssues,
    skippedProposals,
  };
}
